name: Deploy topics to dev

on:
  push:
    branches:
      - main

jobs:
  deploy-krav-topic-to-dev:
    name: Deploy redis to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/redis-config.yml
